apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca
  labels:
    run: alpaca
spec:
  replicas: 2
  selector:
    matchLabels:
      run: alpaca
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: alpaca
      annotations:
        kubernetes.io/change-cause: "Nada"
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:green
          imagePullPolicy: Always
          name: kuard
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3 
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
