kind: Pod
apiVersion: v1
metadata:
  name: kuard-tls
spec:
  containers:
  - name: kuard-tls
    image: gcr.io/kuar-demo/kuard-amd64:blue
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "1000m"
        memory: "256Mi"
    volumeMounts:
      - mountPath: /tls
        name: tls-certs
        readOnly: true
  imagePullSecrets:
    - name: my-image-pull-secret # Creation of the secrets here are documented in the README.
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
