kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default # Because Roles and Rolebindings are restricted by namespace.
  name: pods-and-services
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["create","delete","get","list","patch","update","watch"]