apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-fast-storage
  labels:
    app: nginx
    example: "true"
spec:
  selector:
    matchLabels:
      app: nginx
      example: "true"
  template:
    metadata:
      labels:
        app: nginx
        example: "true"
    spec:
      nodeSelector:
        example: "true"
      containers:
      - name: nginx
        image: nginx:latest
